services:
  android:
    image: storytellerf/android-in-docker:snapshot-ssh
    ports:
      - "6080:6080" # noVNC web interface
      - "5901:5901" # VNC direct connection
      - "5555:5555" # ADB
      - "4723:4723" # Appium
      - "2222:22"
    volumes:
      - avd_data:${CONTAINER_HOME:-/home/debian}/.android/avd
      - ./logs:${CONTAINER_HOME:-/home/debian}/log/supervisor
      - sdk_data:${CONTAINER_HOME:-/home/debian}/Android/Sdk
      - ./data/authorized_keys:${CONTAINER_HOME:-/home/debian}/.ssh/authorized_keys
